version: "3.8"

services:
  app_proxy:
    environment:
      APP_HOST: bitmap-brc-420-indexer_server_1
      APP_PORT: 8080

  server:
    image: bitmap-brc-420-indexer:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DB_PATH=/app/db/brc420.db
      - PORT=8080
      - WEB_PORT=8080
      - RUN_INDEXER=true
      - START_BLOCK=792435
      - RETRY_BLOCK_DELAY=1
      - MAX_RETRIES=5
      - RETRY_DELAY=1000
      - CONCURRENCY_LIMIT=10
      - API_TIMEOUT=30000
      - STATUS_TIMEOUT=10000
      # Umbrel service discovery - these will be automatically detected
      - ORD_API_URL=http://ordinals_web_1:4000
      - API_WALLET_URL=http://mempool_web_1:3006/api
      # Bitcoin RPC connection to Umbrel's Bitcoin Core
      - BITCOIN_RPC_HOST=${APP_BITCOIN_NODE_IP}
      - BITCOIN_RPC_PORT=8332
      - BITCOIN_RPC_USER=${APP_BITCOIN_RPC_USER}
      - BITCOIN_RPC_PASS=${APP_BITCOIN_RPC_PASS}
      # Umbrel device info
      - DEVICE_HOSTNAME=${DEVICE_HOSTNAME}
      - DEVICE_DOMAIN_NAME=${DEVICE_DOMAIN_NAME}
    volumes:
      - ${APP_DATA_DIR}/db:/app/db
      - ${APP_DATA_DIR}/logs:/app/logs
    networks:
      - default
    depends_on: []
