version: "3.7"

services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/db
      - ./logs:/app/logs
    environment:
      NODE_ENV: development
      PORT: 8080
      DB_PATH: /app/db/brc420.db
      API_URL: https://ordinals.com/api
      API_WALLET_URL: https://mempool.space/api
      START_BLOCK: 792435
      RETRY_BLOCK_DELAY: 3
      MAX_RETRIES: 3
      RETRY_DELAY: 5000
      CONCURRENCY_LIMIT: 5
      RUN_INDEXER: false
    depends_on:
      - db-setup
    restart: unless-stopped

  indexer:
    build: .
    volumes:
      - ./data:/app/db
      - ./logs:/app/logs
    environment:
      NODE_ENV: development
      DB_PATH: /app/db/brc420.db
      API_URL: https://ordinals.com/api
      API_WALLET_URL: https://mempool.space/api
      START_BLOCK: 792435
      RETRY_BLOCK_DELAY: 3
      MAX_RETRIES: 3
      RETRY_DELAY: 5000
      CONCURRENCY_LIMIT: 3  # Lower for development
      RUN_INDEXER: true
    command: ["node", "index.js"]
    depends_on:
      - db-setup
    restart: unless-stopped
    profiles:
      - indexer  # Only start when using 'indexer' profile

  db-setup:
    build: .
    volumes:
      - ./data:/app/db
    environment:
      DB_PATH: /app/db/brc420.db
    command: ["node", "db/setup.js"]
    restart: "no"

volumes:
  data:
  logs:
